language: node_js
node_js:
 - "10"
cache: npm

install:
  - npm ci

branches:
  only:
  - master

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "zFzEQ745ihmyCRpfvEqRro1MvDfZ2H2NAzGFiPNWBKmXRvDQUkPBr80DFXwCaEThLGzv4H+PjcX/dYjpA9UE3KWag46c8VJHtKLTPlwZ5mjbQ1POa+amYCW5ArTXMSbLnfF4SforvJCPX9zxRjDwE0f8IAhQOWKz+4uCXbR/uknnjgmf0Bu4aXUwHgqDFI0dhBeayU/opHH82pt3m7QkOq5huNI5Ysz2m1xRC/jQOYQPS7TdI8uMyJw1rC9l7aLpNSbDntZahizGnFtn5jp5ggNonOH/iX2r8ZQcYAuzOUBcIMJHYuiMP6DS53kSr3i7mfYGE6GL2xyCuea7A9yTeXdcqUGzq9P5y94GCHPsikl/NJIz2Y7Py0he9azktO00dKDeev00hu/U8ZIGvrRtzliDsGqbuwnx7M8fkGLYe7wnf4EU8B6oCQxHPdJMjMwvzlLqkQVV4PTDiX3InPI4POEWvoPpn8jIUxFCRs1hsLCkqsY1I0IEoKRAVT6GT/lRkIUOtmmP4FM7EbSup+B5VkiOXOVfSVxLsC7JmtvfMKRQReYROnsLy5XDSE7TplX5aSHd0MEjhhfRAE1zRHqCfeIWUF2sfALXmmdmcmvhkzpIwwOFUQLvov0cCA5j4Ks7LeU1UeHKVvDWW7osQsVjh+f67lpcaP6Vh4Fho6zacFs="
  project: larissavarjao-8
